// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9BKiNRsGl-9AFmX4WEBjf-gc5uRGRJCg',
    appId: '1:10690703382:web:41f154bed8913a84bbc537',
    messagingSenderId: '10690703382',
    projectId: 'myproject-55ae2',
    authDomain: 'myproject-55ae2.firebaseapp.com',
    storageBucket: 'myproject-55ae2.appspot.com',
    measurementId: 'G-97T2LKCJ3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAewWKRG4MZFyPrLknNU-lsYqj5mbV4C_Y',
    appId: '1:10690703382:android:37e97a20ca3e3371bbc537',
    messagingSenderId: '10690703382',
    projectId: 'myproject-55ae2',
    storageBucket: 'myproject-55ae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANADC2Uyl3_PESxeO9q3p-Fo5ZYzxwixA',
    appId: '1:10690703382:ios:84f0aeebd09ecbcdbbc537',
    messagingSenderId: '10690703382',
    projectId: 'myproject-55ae2',
    storageBucket: 'myproject-55ae2.appspot.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANADC2Uyl3_PESxeO9q3p-Fo5ZYzxwixA',
    appId: '1:10690703382:ios:b1aa7f3b282a6dd3bbc537',
    messagingSenderId: '10690703382',
    projectId: 'myproject-55ae2',
    storageBucket: 'myproject-55ae2.appspot.com',
    iosBundleId: 'com.example.myproject.RunnerTests',
  );
}
